Fix OffsetIterator
cuthbertLab/music21j pull request #174
Opened 2022-04-06 00:03 UTC by jacobtylerwalls

For consecutive notes n1, n2, n3, n4, n5, it was yielding [n1, n1, n1], [n3, n3, n3], [n5]  instead of [n1], [n2], [n3], [n4], [n5].

2022-04-06 02:00 UTC, mscuthbert requested changes
Requesting a test that the fix has fixed the bug -- my code read didn't suggest that it would.

2022-04-06 02:12 UTC, jacobtylerwalls commented on src/stream/iterator.ts
> -                this.index = forwardIndex;
`this.index` was already advanced, see the first line of the while loop. then it backtracks (?) to get "this". So "next" is actually "this.index". The regular iterator works this way too, is why I didn't change it. I get that the test needs more details.

2022-04-06 02:18 UTC, mscuthbert commented on src/stream/iterator.ts
> -                this.index = forwardIndex;
But what about for the third item?  If you had TrebleClef, 4/4, 3-flats, and Note at the beginning of the piece, it seems like OffsetIterator would just get TrebleClef, 4/4, 4/4, 4/4.

2022-04-06 02:32 UTC, jacobtylerwalls commented on src/stream/iterator.ts
> -                this.index = forwardIndex;
let's test it! my first expectation would be for `forwardIndex++` to take care of that.

2022-04-06 03:13 UTC, jacobtylerwalls commented on src/stream/iterator.ts
> -                this.index = forwardIndex;
yeah I see what you mean now!

2022-04-06 14:43 UTC, jacobtylerwalls commented on src/stream/iterator.ts
> +                yieldEls.push(nextE);
This was pushing `e` over and over instead of `nextE`.

2022-04-06 14:43 UTC, jacobtylerwalls commented on src/stream/iterator.ts
> -                this.index = forwardIndex;
By setting `this.index = forwardIndex` at the bottom of the loop we were getting double runs of the first value for `this.index`. You were right it needed to be placed _somewhere_, though. (I didn't know what updateActiveInformation() was up to when I first looked, so didn't really know what values the indexes were supposed to take.)

2022-04-13 22:59 UTC, mscuthbert approved these changes
Thanks!  Looks great!  Wonderful fix.

2022-04-13 22:59 UTC, merged